language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import python-dateutil gitpython Pillow disqus-python pygments
  bs4
addons:
  apt:
    packages:
    - asciidoc
    - source-highlight
script:
- make publish github
env:
  global:
  - GH_USER=containerleaks
  - GH_REPO=site
  - GH_BRANCH=gh-pages
  - secure: hbUGVHG7hPo9T7rdbtvNezN4PUqFSivJjSwNkNrTGtvL0tzUN+DlDOenGotCgshKoGyADwlpsyGMnBmhRlBX7wh1SVmRJoAwayRmEe6Gi82srkUNllh/HZbVR0aSWA4adDRYTs+KewBska5wUKi9+tCbMRdS0ZDvFRtACWYnpKQ6W6/cTy7dPEZ0fFn5TlfrzLtN1B3Otw8fXdz6JL3xynOjJ10DuEqZh1MbK05GQ/mRW4RLyysq0VwHfPkR32SmD3/6HO+L+ztsBvm3NED6h3Qq7j3dhj1ve0oqO7RS6RGOh/9ZWAUcCp7MVQJv+TH7LAURPR/WrosCgGRWNbiGTkY/cmQ331BFvTgu8ebPzOiXjogrCPiilF2M8QLHOu/8Gr94cw4baofAnVcdQpd4EbC9QouMYFjc4QpZfwKT2lQNrSecI7QsmxttiI8MpMFOADfG1O5Qe6V5ysUYhfyEfW71ZVkayPKE4orm2FfFMuJChYg49GbrQvcTvZ7pIAM66ejPoBlmyefGUSd6l3MAos45ulta5cDVzAQYEIf+Mrnw4OR6RqyCaSvQJKJc/CHxWonyWTZ9668t+uB3djqpUcEoTp5cdBtXa0x5rfqmrNNNJtFl3ta+89zaDNmtFyASOKyOL6WZTBi3vfFnx85A7OJnPAJPg5U8daWmrRzO4xQ=
